### PR TITLE
Mock collector 

### PR DESCRIPTION
**Pull request by slemrmartin**

### CODE REVIEW

**Comment by slemrmartin** [comment]
@agrare First version, not configurable. 
Continuing in another PR

**Comment by slemrmartin** [comment]
I'm not sure where the error is, but for example `ContainerGroup.container_project_id` is not saved.
`InventoryObjectLazy` in core contains project's name, but `InventoryCollection::Index::Proxy.data_index_find(reference)` searches in `Index::Type::Data.index` which is blank.

When I debugged it, there was no search in db for existing records

**Comment by Ladas** [comment]
@slemrmartin @agrare I am thinking we could have a new repo mock-openshift-collector? It should act as a different provider, right?

**Comment by slemrmartin** [comment]
@Ladas we discussed about it. At this moment I'm adding mock collector over standard collector. When standard code will be stable enough, then I'll use it and create new repo.

**Comment by agrare** [comment]
@Ladas yeah we talked about it and @slemrmartin wanted to reuse some existing code in this repo at first.  I'm not seeing a lot of reuse here (yet?) though.

Having a standlone mock collector would let us mock more than just openshfit as well, we could have an amazon mock collector, azure, etc...

**Comment by Ladas** [comment]
we can probably just fetch the real collector as gem? That way we can share e.g. the worker setup and other things?

**Comment by slemrmartin** [comment]
@agrare `mock-collector` is inherited from your `collector`. I'm basically creating mock-OpenShift and using whole collector's parsing and communication with ingress api

**Comment by Ladas** [comment]
@slemrmartin @agrare right, so we can do that in another repo, right? Just fetching the original repo gem. Also not sure if we should have 1 mock repo, or repo per provider

**Comment by slemrmartin** [comment]
@Ladas also I'm not sure if ingress-api client gem is enough to share with all collectors, even non-mock. I think we can create more common code

**Comment by slemrmartin** [comment]
@agrare can you merge it please? I'll add more code in next PR

**Comment by agrare** [comment]
Okay I'll merge this for now but @slemrmartin if you want to create a mock collector in your github account we can start to move to that.

**Comment by slemrmartin** [comment]
copied into https://github.com/slemrmartin/mock-collector

**Comment by agrare** [comment]
:+1:

**Pull request merged**
